framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr', 'en', 'nl']
        paths:
            - '%kernel.project_dir%/translations/fr'
            - '%kernel.project_dir%/translations/en'
            - '%kernel.project_dir%/translations/nl'
