<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503140212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE entity_mention (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              source_type VARCHAR(50) NOT NULL,
              source_id INT NOT NULL,
              target_type VARCHAR(50) NOT NULL,
              target_id INT NOT NULL,
              project_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_71CF6BEE166D1F9C ON entity_mention (project_id)');
        $this->addSql('CREATE INDEX idx_mention_source ON entity_mention (source_type, source_id)');
        $this->addSql('CREATE INDEX idx_mention_target ON entity_mention (target_type, target_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE world_event (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              title VARCHAR(255) NOT NULL,
              description TEXT DEFAULT NULL,
              year INT NOT NULL,
              month INT DEFAULT NULL,
              day INT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              project_id INT NOT NULL,
              location_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_BACED8A8166D1F9C ON world_event (project_id)');
        $this->addSql('CREATE INDEX IDX_BACED8A864D218E ON world_event (location_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              entity_mention
            ADD
              CONSTRAINT FK_71CF6BEE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              world_event
            ADD
              CONSTRAINT FK_BACED8A8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              world_event
            ADD
              CONSTRAINT FK_BACED8A864D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE location ADD parent_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              location
            ADD
              CONSTRAINT FK_5E9E89CB727ACA70 FOREIGN KEY (parent_id) REFERENCES location (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql('CREATE INDEX IDX_5E9E89CB727ACA70 ON location (parent_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE entity_mention DROP CONSTRAINT FK_71CF6BEE166D1F9C');
        $this->addSql('ALTER TABLE world_event DROP CONSTRAINT FK_BACED8A8166D1F9C');
        $this->addSql('ALTER TABLE world_event DROP CONSTRAINT FK_BACED8A864D218E');
        $this->addSql('DROP TABLE entity_mention');
        $this->addSql('DROP TABLE world_event');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB727ACA70');
        $this->addSql('DROP INDEX IDX_5E9E89CB727ACA70');
        $this->addSql('ALTER TABLE location DROP parent_id');
    }
}
