<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414155859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "character" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, nickname VARCHAR(255) NOT NULL, description TEXT NOT NULL, role VARCHAR(50) NOT NULL, biography TEXT NOT NULL, goals TEXT NOT NULL, motivations TEXT NOT NULL, character_arc TEXT NOT NULL, portrait_filename VARCHAR(255) DEFAULT NULL, aliases JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_937AB034166D1F9C ON "character" (project_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, avatar_filename VARCHAR(255) DEFAULT NULL, is_banned BOOLEAN NOT NULL, locale VARCHAR(5) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE activity_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD06F647166D1F9C ON activity_log (project_id)');
        $this->addSql('CREATE INDEX IDX_FD06F647A76ED395 ON activity_log (user_id)');
        $this->addSql('CREATE TABLE character_relation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, relation_type VARCHAR(50) NOT NULL, description TEXT NOT NULL, is_bidirectional BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_a_id INT NOT NULL, character_b_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A88AED82C2247C0 ON character_relation (character_a_id)');
        $this->addSql('CREATE INDEX IDX_3A88AED83E97E82E ON character_relation (character_b_id)');
        $this->addSql('CREATE TABLE feature_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_type VARCHAR(50) NOT NULL, feature_key VARCHAR(50) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT NOT NULL, value_type VARCHAR(20) NOT NULL, default_value VARCHAR(255) NOT NULL, options JSON NOT NULL, is_required BOOLEAN NOT NULL, display_order INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, type VARCHAR(50) NOT NULL, image_filename VARCHAR(255) DEFAULT NULL, aliases JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E9E89CB166D1F9C ON location (project_id)');
        $this->addSql('CREATE TABLE note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, linked_entity_type VARCHAR(50) NOT NULL, linked_entity_id INT DEFAULT NULL, due_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, author_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA14166D1F9C ON note (project_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F675F31B ON note (author_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F4BD7827 ON note (assigned_to_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, link VARCHAR(255) DEFAULT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE owner_response (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_289BB238F8697D13 ON owner_response (comment_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, project_type VARCHAR(50) NOT NULL, cover_filename VARCHAR(255) DEFAULT NULL, is_public BOOLEAN NOT NULL, custom_structure JSON NOT NULL, settings JSON NOT NULL, status VARCHAR(50) NOT NULL, moderation_status VARCHAR(50) NOT NULL, report_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEB03A8386 ON project (created_by_id)');
        $this->addSql('CREATE TABLE project_feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, feature_key VARCHAR(50) NOT NULL, value TEXT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_89C97903166D1F9C ON project_feature (project_id)');
        $this->addSql('CREATE TABLE project_member (role VARCHAR(50) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (project_id, user_id))');
        $this->addSql('CREATE INDEX IDX_67401132166D1F9C ON project_member (project_id)');
        $this->addSql('CREATE INDEX IDX_67401132A76ED395 ON project_member (user_id)');
        $this->addSql('CREATE TABLE project_mention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id INT NOT NULL, occurrence_count INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_741C55A8166D1F9C ON project_mention (project_id)');
        $this->addSql('CREATE TABLE project_type_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_type VARCHAR(50) NOT NULL, depth INT NOT NULL, element_type VARCHAR(50) NOT NULL, label_singular VARCHAR(100) NOT NULL, label_plural VARCHAR(100) NOT NULL, has_content BOOLEAN NOT NULL, has_duration BOOLEAN NOT NULL, default_duration_seconds INT NOT NULL, icon VARCHAR(50) NOT NULL, color VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE public_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, is_approved BOOLEAN NOT NULL, is_spam BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFAA0DDE166D1F9C ON public_comment (project_id)');
        $this->addSql('CREATE INDEX IDX_CFAA0DDEA76ED395 ON public_comment (user_id)');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason TEXT NOT NULL, admin_feedback TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, reporter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784166D1F9C ON report (project_id)');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('CREATE TABLE scenario_element (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, element_type VARCHAR(50) NOT NULL, depth INT NOT NULL, title VARCHAR(255) NOT NULL, content JSON NOT NULL, summary TEXT NOT NULL, order_index INT NOT NULL, duration_seconds INT NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E869E39166D1F9C ON scenario_element (project_id)');
        $this->addSql('CREATE INDEX IDX_5E869E39727ACA70 ON scenario_element (parent_id)');
        $this->addSql('CREATE TABLE scenario_element_tag (scenario_element_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (scenario_element_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_D546CF96A6E29AF0 ON scenario_element_tag (scenario_element_id)');
        $this->addSql('CREATE INDEX IDX_D546CF96BAD26311 ON scenario_element_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(7) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_389B783166D1F9C ON tag (project_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, status VARCHAR(20) NOT NULL, priority VARCHAR(20) NOT NULL, linked_entity_type VARCHAR(50) DEFAULT NULL, linked_entity_id INT DEFAULT NULL, due_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, created_by_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25166D1F9C ON task (project_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25B03A8386 ON task (created_by_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25F4BD7827 ON task (assigned_to_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE "character" ADD CONSTRAINT FK_937AB034166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_log ADD CONSTRAINT FK_FD06F647A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_relation ADD CONSTRAINT FK_3A88AED82C2247C0 FOREIGN KEY (character_a_id) REFERENCES "character" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character_relation ADD CONSTRAINT FK_3A88AED83E97E82E FOREIGN KEY (character_b_id) REFERENCES "character" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE owner_response ADD CONSTRAINT FK_289BB238F8697D13 FOREIGN KEY (comment_id) REFERENCES public_comment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_feature ADD CONSTRAINT FK_89C97903166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_member ADD CONSTRAINT FK_67401132A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_mention ADD CONSTRAINT FK_741C55A8166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE public_comment ADD CONSTRAINT FK_CFAA0DDE166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE public_comment ADD CONSTRAINT FK_CFAA0DDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scenario_element ADD CONSTRAINT FK_5E869E39166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scenario_element ADD CONSTRAINT FK_5E869E39727ACA70 FOREIGN KEY (parent_id) REFERENCES scenario_element (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scenario_element_tag ADD CONSTRAINT FK_D546CF96A6E29AF0 FOREIGN KEY (scenario_element_id) REFERENCES scenario_element (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scenario_element_tag ADD CONSTRAINT FK_D546CF96BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT FK_389B783166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "character" DROP CONSTRAINT FK_937AB034166D1F9C');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647166D1F9C');
        $this->addSql('ALTER TABLE activity_log DROP CONSTRAINT FK_FD06F647A76ED395');
        $this->addSql('ALTER TABLE character_relation DROP CONSTRAINT FK_3A88AED82C2247C0');
        $this->addSql('ALTER TABLE character_relation DROP CONSTRAINT FK_3A88AED83E97E82E');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB166D1F9C');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14166D1F9C');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F675F31B');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F4BD7827');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE owner_response DROP CONSTRAINT FK_289BB238F8697D13');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEB03A8386');
        $this->addSql('ALTER TABLE project_feature DROP CONSTRAINT FK_89C97903166D1F9C');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132166D1F9C');
        $this->addSql('ALTER TABLE project_member DROP CONSTRAINT FK_67401132A76ED395');
        $this->addSql('ALTER TABLE project_mention DROP CONSTRAINT FK_741C55A8166D1F9C');
        $this->addSql('ALTER TABLE public_comment DROP CONSTRAINT FK_CFAA0DDE166D1F9C');
        $this->addSql('ALTER TABLE public_comment DROP CONSTRAINT FK_CFAA0DDEA76ED395');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784166D1F9C');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE scenario_element DROP CONSTRAINT FK_5E869E39166D1F9C');
        $this->addSql('ALTER TABLE scenario_element DROP CONSTRAINT FK_5E869E39727ACA70');
        $this->addSql('ALTER TABLE scenario_element_tag DROP CONSTRAINT FK_D546CF96A6E29AF0');
        $this->addSql('ALTER TABLE scenario_element_tag DROP CONSTRAINT FK_D546CF96BAD26311');
        $this->addSql('ALTER TABLE tag DROP CONSTRAINT FK_389B783166D1F9C');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25166D1F9C');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25B03A8386');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25F4BD7827');
        $this->addSql('DROP TABLE "character"');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE activity_log');
        $this->addSql('DROP TABLE character_relation');
        $this->addSql('DROP TABLE feature_definition');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE owner_response');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_feature');
        $this->addSql('DROP TABLE project_member');
        $this->addSql('DROP TABLE project_mention');
        $this->addSql('DROP TABLE project_type_config');
        $this->addSql('DROP TABLE public_comment');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE scenario_element');
        $this->addSql('DROP TABLE scenario_element_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
