<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614084552 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" ALTER avatar_color DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_user_likes_liked RENAME TO IDX_AB08B525E2ED1879');
        $this->addSql('ALTER INDEX idx_user_likes_liker RENAME TO IDX_AB08B525979F103A');
        $this->addSql('ALTER TABLE comment ADD moderation_note VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE comment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE comment ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE comment_vote ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE comment_vote ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comment_vote ALTER value DROP DEFAULT');
        $this->addSql('ALTER TABLE comment_vote ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_comment_vote_comment RENAME TO IDX_7C262788F8697D13');
        $this->addSql('ALTER INDEX idx_comment_vote_user RENAME TO IDX_7C262788A76ED395');
        $this->addSql('ALTER TABLE documentation_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE documentation_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE documentation_translation ALTER locale DROP DEFAULT');
        $this->addSql('ALTER TABLE documentation_translation ALTER title DROP DEFAULT');
        $this->addSql('ALTER TABLE documentation_translation ALTER content DROP DEFAULT');
        $this->addSql('DROP INDEX idx_genre_active');
        $this->addSql('ALTER TABLE genre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE genre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE genre ALTER project_types DROP DEFAULT');
        $this->addSql('ALTER INDEX genre_slug_key RENAME TO UNIQ_835033F8989D9B62');
        $this->addSql('DROP INDEX idx_genre_trans_locale');
        $this->addSql('ALTER TABLE genre_translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE genre_translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notification ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE project ALTER visibility DROP DEFAULT');
        $this->addSql('ALTER TABLE project_member ADD status VARCHAR(20) NOT NULL DEFAULT \'active\'');
        $this->addSql('ALTER TABLE report ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE report ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE report ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE report ALTER created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP moderation_note');
        $this->addSql('ALTER TABLE comment ALTER id SET DEFAULT nextval(\'comment_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE comment ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER status SET DEFAULT \'visible\'');
        $this->addSql('ALTER TABLE comment ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE comment_vote ALTER id SET DEFAULT nextval(\'comment_vote_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE comment_vote ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comment_vote ALTER value SET DEFAULT \'up\'');
        $this->addSql('ALTER TABLE comment_vote ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER INDEX idx_7c262788a76ed395 RENAME TO idx_comment_vote_user');
        $this->addSql('ALTER INDEX idx_7c262788f8697d13 RENAME TO idx_comment_vote_comment');
        $this->addSql('ALTER TABLE documentation_translation ALTER id SET DEFAULT nextval(\'documentation_translation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE documentation_translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE documentation_translation ALTER locale SET DEFAULT \'fr\'');
        $this->addSql('ALTER TABLE documentation_translation ALTER title SET DEFAULT \'\'');
        $this->addSql('ALTER TABLE documentation_translation ALTER content SET DEFAULT \'\'');
        $this->addSql('ALTER TABLE genre ALTER id SET DEFAULT nextval(\'genre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE genre ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE genre ALTER project_types SET DEFAULT \'[]\'');
        $this->addSql('CREATE INDEX idx_genre_active ON genre (is_active, order_index)');
        $this->addSql('ALTER INDEX uniq_835033f8989d9b62 RENAME TO genre_slug_key');
        $this->addSql('ALTER TABLE genre_translation ALTER id SET DEFAULT nextval(\'genre_translation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE genre_translation ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_genre_trans_locale ON genre_translation (locale)');
        $this->addSql('ALTER TABLE notification ALTER type SET DEFAULT \'info\'');
        $this->addSql('ALTER TABLE project ALTER visibility SET DEFAULT \'unpublished\'');
        $this->addSql('ALTER TABLE project_member DROP status');
        $this->addSql('ALTER TABLE report ALTER id SET DEFAULT nextval(\'report_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE report ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE report ALTER status SET DEFAULT \'pending\'');
        $this->addSql('ALTER TABLE report ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE "user" ALTER avatar_color SET DEFAULT \'#3B82F6\'');
        $this->addSql('ALTER INDEX idx_ab08b525979f103a RENAME TO idx_user_likes_liker');
        $this->addSql('ALTER INDEX idx_ab08b525e2ed1879 RENAME TO idx_user_likes_liked');
    }
}
